# Generated by Django 4.1.1 on 2022-10-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Título de la película', max_length=200),
        ),
    ]
